version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: currency-coverter-api
    restart: always
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", ""]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["node", "dist/server.js"]

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: currency-coverter-ui
    restart: always
    volumes:
      - ./frontend/app:/app/src
      - ./frontend/public:/app/public
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:3000"
    links:
      - backend
    command: ["node", "dist/server.js"]


